version: '3.8'
services:
  db:
    image: postgres:14.1-alpine    
    environment:
      - POSTGRES_USER=makudo
      - POSTGRES_PASSWORD=narudo
      - POSTGRES_DB=learning-nest-db
    ports:
      - '7000:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - learning-nest
networks:
  learning-nest: